apiVersion: apps/v1
kind: Deployment
metadata:
  name: goviolin-deployment
spec:
  selector:
    matchLabels:
      app: goviolin
  replicas: 1
  template:
    metadata:
      name: goviolin-pod
      labels:
        app: goviolin
    spec:
      containers:
        - name: goviolin-container
          image: mohiey/goviolin